apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/amisstea/devfile-sample-go-basic?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: sample
    appstudio.openshift.io/component: decfile-sample-go-basic
    pipelines.appstudio.openshift.io/type: build
  name: devfile-sample-go-basic-on-push
  namespace: amisstea-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/amisstea-tenant/sample/devfile-sample-go-basic:{{revision}}
  - name: dockerfile
    value: /docker/Dockerfile
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'