---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: provision-cluster-test
spec:
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/amisstea/build-definitions.git
          - name: revision
            value: RHTAPWATCH-1053-fix
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/amisstea/build-definitions.git
                - name: revision
                  value: increase-eaas-timeout
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: instanceType
                value: m5.large
    # - name: deploy-operator
    #   runAfter:
    #     - provision-cluster
    #   params:
    #     - name: snapshot
    #       value: "$(params.SNAPSHOT)"
    #   taskSpec:
    #     params:
    #       - name: snapshot
    #         type: string
    #     results:
    #       - name: bundleImage
    #         description: The bundle image under test
    #     volumes:
    #       - name: credentials
    #         emptyDir: {}
    #     steps:
    #       - name: get-kubeconfig
    #         ref:
    #           resolver: git
    #           params:
    #             - name: url
    #               value: https://github.com/konflux-ci/build-definitions.git
    #             - name: revision
    #               value: main
    #             - name: pathInRepo
    #               value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
    #         params:
    #           - name: eaasSpaceSecretRef
    #             value: $(tasks.provision-eaas-space.results.secretRef)
    #           - name: clusterName
    #             value: "$(tasks.provision-cluster.results.clusterName)"
    #           - name: credentials
    #             value: credentials
    #       - name: get-snapshot-image
    #         image: quay.io/redhat-appstudio/appstudio-utils@sha256:586149e3f18d966f681d956ab074b4e1d8433663d615ed86e19a3804ba952dfe
    #         env:
    #           - name: SNAPSHOT
    #             value: "$(params.snapshot)"
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         script: |
    #           #!/usr/bin/bash
    #           set -exo pipefail
    #           jq -r '.components[0].containerImage' <<< "$SNAPSHOT" | tee $(results.bundleImage.path)
    #       - name: operator-sdk-run-bundle
    #         image: registry.redhat.io/openshift4/ose-operator-sdk-rhel9@sha256:933c2cefad0efc2523f66b37b69f20d0146fbb02f5532ca9dd0fe4b7aad827c6
    #         env:
    #           - name: KUBECONFIG
    #             value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
    #         volumeMounts:
    #           - name: credentials
    #             mountPath: /credentials
    #         args:
    #           - run
    #           - bundle
    #           - --namespace
    #           - default
    #           - "$(results.bundleImage)"
